version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: testadmin
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: testdb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-db-data:
    name: postgres-db-data