version: '3'

services:
  postgres-db:
    stdin_open: true
    tty: true
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  note_life_backend:
    stdin_open: true
    tty: true
    container_name: note_life_backend
    build:
      context: ../
      dockerfile: ./Dockerfile
      args:
        ENV: prod
        POSTGRES_HOST: postgres-db
        POSTGRES_PORT: 5432
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DATABASE: ${POSTGRES_DATABASE}
        ROCKET_ADDRESS: ${ROCKET_ADDRESS}
    environment:
      ENV: prod
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      ROCKET_ADDRESS: ${ROCKET_ADDRESS}
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
volumes:
  postgres-db-data:
    driver: local