apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: postgres
  labels:
    app: postgres
spec:
  # Choose how to expose your service
  type: NodePort
  ports:
    # The port number to expose the service
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32618
  # Pod to route service traffic  
  selector:
    app: postgres