apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: bm90ZV9saWZl # test
  POSTGRES_USER: dGVzdFVzZXIx # test
  POSTGRES_PASSWORD: dGVzdFBhc3N3b3JkMQ== # test