name: Deploy
on:
    push:
      branches:
        - main
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
              profile: minimal
              toolchain: stable
        - name: Build
          run:
            cargo build --verbose --locked

        - name: Set up
          uses: docker/setup-buildx-action@v2

        - name: Log in to docker hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: tifisz/rust-note-project:latest

    deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Log in to docker hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Install sshpass
          run: sudo apt-get install sshpass

        - name: Copy docker-compose.yml to droplet
          run: sshpass -v -p ${{ secrets.DROPLET_PASSWORD }} scp -o StrictHostKeyChecking=no ./docker/docker-compose.yml root@${{ vars.DROPLET_IP }}:~

        - name: Deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ vars.DROPLET_IP }}
            username: root
            password: ${{ secrets.DROPLET_PASSWORD }}
            script: |
              cd ~
              export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
              export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
              export POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }}
              export ROCKET_ADDRESS=${{ secrets.ROCKET_ADDRESS }}
              docker-compose down
              docker-compose pull
              docker-compose up -d